# Generated by Django 3.0.8 on 2022-04-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategory_add_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='is_home',
            new_name='is_hot',
        ),
    ]
