# Generated by Django 3.0.8 on 2022-04-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodscategorybrand_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
    ]
